### ISSUE TITLE
[pekwm] closes on pointer movement outside box

### ISSUE THREAD

**Issue by ghost** [ZaWertun/xwinmosaic#2]
Hi, thank you for the fork.
A small question; if I move pointer outside the box the application closes, 
is there a option to keep running until mouse click/press only?

at_pointer = true (move pointer outside any box and it closes)
at_pointer = false (I can move to a box but move pointer outside box it closes)

**Comment by ZaWertun** [comment]
Hmmm.

I'm using it with KDE and with option `at_pointer = false`
it will be shown until I click inside or outside of xwinmosaic window.
Maybe some other option affecting it, I don't know.

There is my config just in case:
```ini
[default]
vim_mode = false
box_width = 160
box_height = 80
colorize = true
color_offset = 0
show_icons = true
show_desktop = true
show_titles = true
icon_size = 48
font = Roboto 10
screenshot = false
screenshot_offset_x = 0
screenshot_offset_y = 0
at_pointer = false
icon_position = top
# color_file = /path/to/file
show_close_button = true
```

**Comment by ghost** [comment]
Thank you for the reply, and my xwinmosaic setting are default.
Using pekwm with sloppy mouse which does focus on window but without raise, must be something interfering here.
I do some testing and update the post.

**Comment by ZaWertun** [comment]
Try running `xwinmosaic` with `-S` option:
```
-S, --screenshot             Get screenshot and set it as a background (for WMs that do not support XShape)
```

**Comment by ghost** [comment]
I do confirm it's related to the sloppy mouse setting.
If deactivated; it will be shown until I click inside or outside.

I expected xwinmosaic window to be fullscreen, but I'm tricked by xcompmgr
as it dims the screen (sets shadow on a transparent parent).

Yeah, doing a --screenshot will fill the parent with a image and focus will therefor remain on xwinmosaic window until clicked.

Thank you again for your time and hint. :)
